//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "assets")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub name: String,
    pub serial_number: Option<String>,
    pub location: Option<String>,
    pub note: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub company_id: i32,
    pub category_id: Option<i32>,
    pub photo_path: Option<String>,
    pub department_id: Option<i32>,
    pub team_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::asset_inspections::Entity")]
    AssetInspections,
    #[sea_orm(
        belongs_to = "super::asset_categories::Entity",
        from = "Column::CategoryId",
        to = "super::asset_categories::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AssetCategories,
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyId",
        to = "super::companies::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Companies,
    #[sea_orm(has_many = "super::qr_codes::Entity")]
    QrCodes,
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentId",
        to = "super::departments::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::TeamId",
        to = "super::teams::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Teams,
}

impl Related<super::asset_inspections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetInspections.def()
    }
}

impl Related<super::asset_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetCategories.def()
    }
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::qr_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrCodes.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teams.def()
    }
}
