//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod asset_categories;
pub mod asset_field_values;
pub mod asset_inspections;
pub mod asset_uploads;
pub mod assets;
pub mod category_field_defs;
pub mod companies;
pub mod departments;
pub mod inspection_templates;
pub mod qr_codes;
pub mod teams;
pub mod users;
